name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  Solution_Name: Quiz/QuizSolution.sln

jobs:
  build-windows:
    strategy:
      matrix:
        configuration: [Debug, Release]

    runs-on: windows-latest
      
    steps:
    # 1. Checkout the code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Install .NET SDK
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # 3. Restore NuGet packages
    - name: Restore
      run: dotnet restore $env:Solution_Name

    # 4. Build the solution
    - name: Build
      run: dotnet build $env:Solution_Name --configuration $env:Configuration --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # 5. Run tests
    - name: Test
      run: dotnet test $env:Solution_Name --configuration $env:Configuration --no-build
      env:
        Configuration: ${{ matrix.configuration }}


  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Install .NET SDK
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # 3. Restore NuGet packages
    - name: Restore
      run: dotnet restore $env:Solution_Name
        
    - name: Snyk Security Scan
      uses: snyk/actions@0.4.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --severity-threshold=medium
        json: true
